#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/chatdb
#    username: root
#    password: khanh1307
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true

#H2 DB
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

jwt:
  key: 07e32a512f7c5d34fd767d45ad21d0bcee00d864e962148b7b3312f6e9592fb6 #256-bit = 64 characters